FROM ubuntu-custom

RUN git clone https://github.com/SpiderLabs/ModSecurity

RUN git clone https://github.com/SpiderLabs/ModSecurity-nginx && git clone https://github.com/SpiderLabs/owasp-modsecurity-crs.git /usr/src/owasp-modsecurity-crs

RUN wget http://nginx.org/download/nginx-1.12.0.tar.gz

