FROM ubuntu:14.04
MAINTAINER jaroslawnyka@gmail.com

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \ 
apt-get install -y --fix-missing \
autoconf            \
automake            \
apt-utils           \
bison               \
build-essential     \
curl                \
devscripts          \
dh-autoreconf       \
doxygen             \
flex                \
g++                 \
git-core            \
libtool             \
make                \
pkg-config          \
tree                \
apache2-dev         \
libcurl4-gnutls-dev \
libgeoip-dev        \
liblmdb-dev         \
libpcre++-dev       \
libxml2-dev         \
libyajl-dev         \
wget                \
lsof                \
vim                 \
telnet              \
zlib1g-dev
