FROM ubuntu-custom-wget-git-modsecurity

RUN useradd -s /bin/false nginx
RUN mkdir /var/cache/nginx
RUN mkdir /usr/lib/nginx
RUN chown nginx /usr/lib/nginx
RUN chown nginx /var/cache/nginx
#make nginx
RUN tar xvzf nginx-1.12.0.tar.gz
RUN cd nginx-1.12.0 && patch -p1 < /nginx_http_upstream_check_module/check.patch
RUN cd /nginx-1.12.0 && ./configure \
--prefix=/etc/nginx \
--sbin-path=/usr/sbin/nginx \
--modules-path=/usr/lib/nginx/modules \
--conf-path=/etc/nginx/nginx.conf \
--error-log-path=/var/log/nginx/error.log \
--http-log-path=/var/log/nginx/access.log \
--pid-path=/var/run/nginx.pid \
--lock-path=/var/run/nginx.lock \
--http-client-body-temp-path=/var/cache/nginx/client_temp \
--http-proxy-temp-path=/var/cache/nginx/proxy_temp \
--http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
--http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
--http-scgi-temp-path=/var/cache/nginx/scgi_temp \
--user=nginx \
--group=nginx \
--with-compat \
--with-file-aio \
--with-threads \
--with-http_addition_module \
--with-http_auth_request_module \
--with-http_dav_module \
--with-http_flv_module \
--with-http_gunzip_module \
--with-http_gzip_static_module \
--with-http_mp4_module \
--with-http_random_index_module \
--with-http_realip_module \
--with-http_secure_link_module \
--with-http_slice_module \
--with-http_ssl_module \
--with-http_stub_status_module \
--with-http_sub_module \
--with-http_v2_module \
--with-mail \
--with-mail_ssl_module \
--with-stream \
--with-stream_realip_module \
--with-stream_ssl_module \
--with-stream_ssl_preread_module \
--add-module=/ngx_upstream_status \
--add-module=/nginx_upstream_check_modul \
--add-module=/ModSecurity-nginx \
&& make -j 8 && make install

#--add-module=/root/nginx_upstream_check_module-maste\
